<?php

namespace Acenda;
use Exception;

/**
 * Class AcendaException
 * HTTP exeption generated by Acenda SDK.
 * @package Acenda
 */
class AcendaException extends Exception{
    public $code;
    public $body;

    /**
     * @param $code HTTP code
     * @param $body Content of the body.
     */
    public function __construct($code, $body){
        $this->code = $code;
        $this->body = $body;

        parent::__construct($code);
    }
}
